config/routes.rb
Myapp::Application.routes.draw do

 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
end
  # You can have the root of your site routed with "root"
  root to: 'commerce#products_list'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"

  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"
  get "/commerce/add_to_cart/:id" => "commerce#add_to_cart"
  get "/commerce/destroy_cart_item/:id" => 'commerce#destroy_cart_item'
  get "/commerce/payment/" => 'commerce#payment'
  resources :charges, only: [:new, :create]
  get"/commerce/product_detail/:id" => "commerce#product_detail"
  get "/commerce/add_to_wishlist/:id" => "commerce#add_to_wishlist"
  get "/commerce/wishlist"
  get "/appviews/update_profile" => "appviews#update_profile"
  patch "/appviews/my/update_profile/:updating_user_id" => "appviews#update_my_profile", as: :update_user_hello_profile
  get "/appviews/Contacts" => "appviews#contacts"
  get "/appviews/profile/:id" => "appviews#profile"
  get "/appviews/show/" => "appviews#show"

end

app/controllers/appviews_controller.rb
class AppviewsController < ApplicationController

  def contacts
    @user = User.all
  end

  def profile
    @user = User.all
    @user = User.find(params[:id])
     @activities = PublicActivity::Activity.all

      @user_traking = PublicActivity::Activity.where(trackable_type: "User", owner_id: current_user.id)
      @cart_traking = PublicActivity::Activity.where(trackable_type: "CartItem")
      @wishlist_traking = PublicActivity::Activity.where(trackable_type: "WishlistItem")
      # If we want to use the same by making scope than un comment the following code and thean uncommet the code in activity.rb
     # @user_traking = Activity.traking("User")
     # @cart_traking = Activity.traking("CartItem")
     # @wishlist_traking = Activity.traking("WishlistItem")
     



  end
  def index
  @activities = PublicActivity::Activity.all
  end

  def show
   
  end


  def update_profile
    @my_user_for_update = current_user
  end

  def update_my_profile
    @user = User.find(params[:updating_user_id])
    @user.update(first_name: params[:asheesh][:my_first_name] ,last_name: params[:asheesh][:my_last_name], phone: params[:asheesh][:my_phone_no],company: params[:asheesh][:company],permanent_address: params[:asheesh][:my_permanent_address],current_address: params[:asheesh][:my_current_address] ,about: params[:asheesh][:my_about],role: params[:asheesh][:my_role],image: params[:asheesh][:image])
    
    redirect_to "/appviews/show"
  end
  
  def profile_two
  end

  def contacts_two
  end

  def projects
  end

  def project_detail
  end

  def file_manager
  end

  def vote_list
  end

  def calendar
  end

  def faq
  end

  def timeline
  end

  def pin_board
  end

  def teams_board
  end

  def clients
  end

  def outlook_view
    render :layout => "layout_3"
  end

  def issue_tracker
  end

  def blog
  end

  def article
  end

end

app/views/appviews/calendar.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-8">
        <h2>Calendar</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
        </li>
        <li>
            Extra pages
        </li>
        <li class="active">
            <strong>Calendar</strong>
        </li>
    </ol>
</div>
        </div>
<div class="wrapper wrapper-content">
<div class="row animated fadeInDown">
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Draggable Events</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#">Config option 1</a>
                        </li>
                        <li>
                            <a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div id='external-events'>
                    <p>Drag a event and drop into callendar.</p>
                    <div class='external-event navy-bg'>Go to shop and buy some products.</div>
                    <div class='external-event navy-bg'>Check the new CI from Corporation.</div>
                    <div class='external-event navy-bg'>Send documents to John.</div>
                    <div class='external-event navy-bg'>Phone to Sandra.</div>
                    <div class='external-event navy-bg'>Chat with Michael.</div>
                    <p class="m-t">
                        <input type='checkbox' id='drop-remove' class="i-checks" checked /> <label for='drop-remove'>remove after drop</label>
                    </p>
                </div>
            </div>
        </div>
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <h2>FullCalendar</h2> is a jQuery plugin that provides a full-sized, drag &amp; drop calendar like the one below. It uses AJAX to fetch events on-the-fly for each month and is
                easily configured to use your own feed format (an extension is provided for Google Calendar).
                <p>
                    <a href="http://arshaw.com/fullcalendar/" target="_blank">FullCalendar documentation</a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Striped Table </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#">Config option 1</a>
                        </li>
                        <li>
                            <a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div id="calendar"></div>
            </div>
        </div>
    </div>
</div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

    /* initialize the external events
     -----------------------------------------------------------------*/


    $('#external-events div.external-event').each(function () {

        // store data so the calendar knows to render an event upon drop
        $(this).data('event', {
            title: $.trim($(this).text()), // use the element's text as the event title
            stick: true // maintain when user navigates (see docs on the renderEvent method)
        });

        // make the event draggable using jQuery UI
        $(this).draggable({
            zIndex: 1111999,
            revert: true,      // will cause the event to go back to its
            revertDuration: 0  //  original position after the drag
        });

    });


    /* initialize the calendar
     -----------------------------------------------------------------*/
    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();

    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        editable: true,
        droppable: true, // this allows things to be dropped onto the calendar
        drop: function () {
            // is the "remove after drop" checkbox checked?
            if ($('#drop-remove').is(':checked')) {
                // if so, remove the element from the "Draggable Events" list
                $(this).remove();
            }
        },
        events: [
            {
                title: 'All Day Event',
                start: new Date(y, m, 1)
            },
            {
                title: 'Long Event',
                start: new Date(y, m, d - 5),
                end: new Date(y, m, d - 2),
            },
            {
                id: 999,
                title: 'Repeating Event',
                start: new Date(y, m, d - 3, 16, 0),
                allDay: false,
            },
            {
                id: 999,
                title: 'Repeating Event',
                start: new Date(y, m, d + 4, 16, 0),
                allDay: false
            },
            {
                title: 'Meeting',
                start: new Date(y, m, d, 10, 30),
                allDay: false
            },
            {
                title: 'Lunch',
                start: new Date(y, m, d, 12, 0),
                end: new Date(y, m, d, 14, 0),
                allDay: false
            },
            {
                title: 'Birthday Party',
                start: new Date(y, m, d + 1, 19, 0),
                end: new Date(y, m, d + 1, 22, 30),
                allDay: false
            },
            {
                title: 'Click for Google',
                start: new Date(y, m, 28),
                end: new Date(y, m, 29),
                url: 'http://google.com/'
            }
        ],
    });


});

</script>

<% end %>



app/views/appviews/contacts.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Contacts</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
        </li>
        <li>
            App Views
        </li>
        <li class="active">
            <strong>Contacts</strong>
        </li>
    </ol>
</div>
        </div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
<% @user.each do |user| %>
    <div class="col-lg-4">
        <div class="contact-box">
            <a href="/appviews/profile/<%= user.id%>">
            <div class="col-sm-4">
                <div class="text-center">
                   <%= image_tag user.image, class: "avatar img-circle", width: 100 %>
                    <div class="m-t-xs font-bold"><%= user.role %></div>
                </div>
            </div>
            <div class="col-sm-8">
                <h3><strong><%= user.first_name %> <%= user.last_name %></strong></h3>
                <p><i class="fa fa-map-marker"></i><%= user.current_address %></p>
                <address>
                    <strong><%= user.company %></strong><br>
                    <%= user.permanent_address %><br>
                    <abbr title="Phone">P:</abbr> <%= user.phone %>
                </address>
            </div>
            <div class="clearfix"></div>
        </a>
    </div>
</div>
<% end %>
<!-- <div class="col-lg-4">
    <div class="contact-box">
        <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
        <div class="col-sm-4">
            <div class="text-center">
                <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a1.jpg') %>">
                <div class="m-t-xs font-bold">CEO</div>
            </div>
        </div>
        <div class="col-sm-8">
            <h3><strong>Alex Johnatan</strong></h3>
            <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
            <address>
                <strong>Twitter, Inc.</strong><br>
                795 Folsom Ave, Suite 600<br>
                San Francisco, CA 94107<br>
                <abbr title="Phone">P:</abbr> (123) 456-7890
            </address>
        </div>
        <div class="clearfix"></div>
    </a>
</div>
</div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a3.jpg') %>">
            <div class="m-t-xs font-bold">Marketing manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Monica Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a4.jpg') %>">
            <div class="m-t-xs font-bold">Sales manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Michael Zimber</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a5.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Sandra Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a6.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Janet Carton</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a1.jpg') %>">
            <div class="m-t-xs font-bold">CEO</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Alex Johnatan</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a2.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>John Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a3.jpg') %>">
            <div class="m-t-xs font-bold">Marketing manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Monica Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a4.jpg') %>">
            <div class="m-t-xs font-bold">Sales manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Michael Zimber</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a5.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Sandra Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a6.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Janet Carton</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>

</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a1.jpg') %>">
            <div class="m-t-xs font-bold">CEO</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Alex Johnatan</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a2.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>John Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div> -->
        </div>
        </div>
        </div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function () {

    $('.contact-box').each(function () {
        animationHover(this, 'pulse');
    });

});

</script>

<% end %>


app/views/appviews/show.html.erb
<h1>

Your Profile has been updated. 


</h1>

<h2>Good bye!! Buddy...</h2>

app/views/appviews/update_profile.html.erb
<div class="container">
<h1>Edit Profile</h1>
<hr>
<div class="row">
<!-- left column -->
<%= form_for :asheesh, url: update_user_hello_profile_path(@my_user_for_update), method: :patch do |f| %>
<div class="col-md-3">
   <div class="text-center">
      <!-- <img src="//placehold.it/100" class="avatar img-circle" alt="avatar"> -->
      <%= image_tag @my_user_for_update.image, class: "avatar img-circle", width: 100 %>
      <h6>Upload a different photo...</h6>
      <%= f.file_field :image, class: "form-control" %>
   </div>
</div>
<!-- edit form column -->
<div class="col-md-9 personal-info">
<div class="alert alert-info alert-dismissable">
   <a class="panel-close close" data-dismiss="alert">×</a> 
   <i class="fa fa-coffee"></i>
   <strong>This is mandatory to fill all fields</strong>
</div>
<h3>Personal info</h3>
<!-- <form class="form-horizontal" role="form"> -->
<div class="form-group">
   <label class="col-lg-3 control-label">First name:</label>
   <div class="col-lg-8">
      <!-- <input class="form-control" type="text" value="Jane"> -->
      <%= f.text_field :my_first_name, class: "form-control", value: @my_user_for_update.first_name %>
   </div>
</div>
<div class="form-group">
<label class="col-lg-3 control-label">Last name:</label>
<div class="col-lg-8">
   <!--  <input class="form-control" type="text" value="Bishop">
      </div> -->
   <%= f.text_field :my_last_name, class: "form-control", value: @my_user_for_update.last_name %>
</div>
<div class="form-group">
   <label class="col-lg-3 control-label">Phone:</label>
   <div class="col-lg-8">
      <!-- <input class="form-control" type="text" value=""> -->
      <%= f.number_field :my_phone_no, class: "form-control" , value: @my_user_for_update.phone%>
   </div>
</div>
<div class="form-group">
   <label class="col-lg-3 control-label">Company:</label>
   <div class="col-lg-8">
      <!--  <input class="form-control" type="text" value="janesemail@gmail.com"> -->
      <%= f.text_field :company, class: "form-control",value: @my_user_for_update.company  %>
   </div>
   <div class="form-group">
      <label class="col-md-3 control-label">Permanent Address:</label>
      <div class="col-md-8">
         <!-- <input class="form-control" type="text" value="janeuser">
            </div>
                   -->         <%= f.text_field :my_permanent_address, class: "form-control", value: @my_user_for_update.permanent_address %>
      </div>
      <div class="form-group">
         <label class="col-md-3 control-label">Current Location:</label>
         <div class="col-md-8">
            <%= f.text_field :my_current_address, class: "form-control" ,value: @my_user_for_update.current_address %>
            <!-- <input class="form-control" type="password" value="11111122333"> -->
         </div>
      </div>
      <div class="form-group">
         <label class="col-md-3 control-label">About:</label>
         <div class="col-md-8">
            <%= f.text_area :my_about, class: "form-control" , value: @my_user_for_update.about %>
            <!-- <input class="form-control" type="password" value="11111122333"> -->
         </div>
         <div class="form-group">
            <label class="col-md-3 control-label">Role:</label>
            <div class="col-md-8">
               <%= f.text_field :my_role, class: "form-control",value: @my_user_for_update.role  %>
               <!-- <input class="form-control" type="password" value="11111122333"> -->
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
               <%= f.submit 'Save Changes', class: "btn btn-primary"%>
               <span></span>
               <input type="reset" class="btn btn-default" value="Cancel">
            </div>
         </div>
         <% end %>
         <!-- </form> -->
      </div>
   </div>
</div>
<hr>